#!/usr/bin/env python3
"""
Automated Playwright script to perform zero-click/one-click Swiggy OAuth login.
Usage:
  python3 swiggy_playwright_auth.py --url "AUTH_URL" --phone "PHONE_NUMBER"
  
When it prints "[ACTION_REQUIRED] Enter OTP: ", provide the 6-digit OTP to stdin.
"""
import sys
import asyncio
import argparse
import urllib.parse
import urllib.request

try:
    from playwright.async_api import async_playwright
except ImportError:
    print("[!] Playwright is not installed. Please run: pip install playwright && playwright install chromium")
    sys.exit(1)

async def do_auth(auth_url, phone):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        
        print(f"[*] Navigating to Swiggy Auth URL...")
        await page.goto(auth_url)
        
        # 1. Click "Agree & Continue" if consent screen appears
        try:
            btn = page.get_by_role("button", name="Agree & Continue")
            await btn.wait_for(state="visible", timeout=3000)
            await btn.click()
            print("[*] Clicked 'Agree & Continue'")
        except Exception:
            pass

        # 2. Enter Phone Number
        print(f"[*] Waiting for phone input...")
        try:
            phone_locator = page.locator('#phone, input[type="tel"]')
            await phone_locator.wait_for(state="visible", timeout=5000)
            await phone_locator.fill(phone)
            
            send_otp_btn = page.locator('#send-otp-btn, button:has-text("SEND OTP"), button:has-text("Login")').first
            await send_otp_btn.click()
            print(f"[*] Clicked 'SEND OTP' for {phone}")
        except Exception as e:
            print(f"[!] Failed to enter phone number: {e}")
            await browser.close()
            return
        
        # 3. Wait for OTP or Error
        try:
            # wait until either otp input is visible or an error pops up
            for _ in range(20):
                err = await page.locator('#error-message').text_content()
                if err and err.strip():
                    print(f"[!] Error from Swiggy: {err.strip()}")
                    await browser.close()
                    return
                
                # Check if OTP input is ready
                count = await page.locator('#otp, input[name="otp"], input[autocomplete="one-time-code"]').count()
                if count > 0:
                    break
                await page.wait_for_timeout(500)
        except Exception:
            pass
                
        # 4. Prompt Agent/User for OTP
        sys.stdout.write("\n[ACTION_REQUIRED] Enter OTP: ")
        sys.stdout.flush()
        
        otp = sys.stdin.readline().strip()
        if not otp:
            print("[!] No OTP provided. Exiting.")
            await browser.close()
            return
            
        print(f"[*] Entering OTP: {otp}")
        try:
            otp_locator = page.locator('#otp, input[name="otp"], input[autocomplete="one-time-code"]').first
            await otp_locator.fill(otp)
            
            verify_btn = page.locator('#verify-otp-btn, button:has-text("Verify")').first
            await verify_btn.click()
        except Exception as e:
            print(f"[!] Failed to enter OTP: {e}")
            
        # 5. Wait for success redirect
        print("[*] Waiting for successful auth redirect...")
        for _ in range(30):
            current_url = page.url
            if "localhost:39025" in current_url:
                print("[*] Auto-redirect to localhost detected! Login complete.")
                break
            elif "success=true" in current_url:
                print("[*] Success page reached! Bypassing frontend redirect blockade...")
                parsed = urllib.parse.urlparse(current_url)
                qs = urllib.parse.parse_qs(parsed.query)
                if 'redirect_uri' in qs:
                    callback_url = qs['redirect_uri'][0]
                    print(f"[*] Calling local callback: {callback_url}")
                    try:
                        urllib.request.urlopen(callback_url)
                        print("[*] Callback triggered successfully. MCP login is done!")
                    except Exception as e:
                        print(f"[!] Local callback failed: {e}")
                break
            await page.wait_for_timeout(500)
        
        await browser.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Swiggy Zero-Click Playwright Auth")
    parser.add_argument("--url", required=True, help="The Swiggy Auth URL generated by the MCP server")
    parser.add_argument("--phone", required=True, help="10-digit phone number")
    args = parser.parse_args()
    
    asyncio.run(do_auth(args.url, args.phone))
